### ISSUE TITLE
Startzeit und Endzeit der "Unregelmäßigen Wiederholungen" werden mit "00:00" ausgegeben

### ISSUE THREAD

**Issue by pipkin46** [cgoIT/calendar-extended-bundle#15]
**Problem mit Startzeit und Endzeit in "Unregelmäßigen Wiederholungen"**

Getestet mit Contao 5.3.11, PHP 8.2
Event mit Einstellung "Zeit hinzufügen", definierter Startzeit und Endzeit sowie regelmäßigen Wiederholungen.

Im Abschnitt "Unregelmäßige Wiederholungen" mehrere Einträge mit unterschiedlichen Start- und Endzeiten angelegt. Die unregelmäßigen Wiederholungen erscheinen in der Ausgabe, Datum ist korrekt, aber statt der richtigen Start-/Endzeit steht dort immer nur "00:00".

**Comment by pipkin46** [comment]
Nachtrag:
In der Datenbank scheinen die richtigen Zeiten zu landen, aber das Template (Original-Templates der 5.3.11) gibt diese nicht aus.

In "repeatFixedDates":
`a:1:{i:0;a:4:{s:10:"new_repeat";i:1725055200;s:9:"new_start";i:32400;s:7:"new_end";i:36000;s:6:"reason";s:0:"";}}`

Müsste ergeben:
2024-08-31 10:00 - 11:00

Das Template gibt aber aus:
2024-08-31 00:00

**Comment by cgoIT** [comment]
Hi, danke für die zusätzliche Info. Ich schaue es mir an. Aber ich weiß noch nicht genau, ob ich da morgen zu komme. Könnte auch nächste Woche werden.

**Comment by Metis77** [comment]
<img width="333" alt="Bildschirmfoto 2024-07-04 um 21 38 57" src="https://github.com/cgoIT/calendar-extended-bundle/assets/1408361/a7e1769a-806b-4c23-85bd-2cc694ced907">

**Comment by cgoIT** [comment]
Fehler sollte in der Version 2.4.1 behoben sein. Sorry, dass es so lange gedauert hat.

**Comment by pipkin46** [comment]
Tausend Dank! Ich teste gleich mal! :-)

**Comment by Metis77** [comment]
Vielen Dank – auch das du dieses Plugin übernommen hast!

Beim Vergleich sind mir jetzt leider dennoch andere Fehler aufgefallen.
Vorab: Ich verwende bei dem Test Event nur Wiederholungen (unregelmäßig).
Und habe jetzt alles Möglichen Varianten getestet.

1. Wird das Modul `Eventliste` mit dem Modul `Eventliste-Menü` angezeigt / gefiltert, dann fehlt in der Liste jeweils das erste / originale Event, es werden nur die Wiederholungen gezeigt.
2. Das Modul `EventLeser` mit dem Template `event_full` hatte früher in der Variable `begin` und evtl. auch in anderen Variablen immer das nächste Ereignis ausgegeben. Das klappt jetzt nicht mehr. Der selber Fehler findet sich analog in `recurring`. Die Ausgabe "Das nächste Ereignis findet statt am ..." ist falsch. 

PS:
ich denke Punkt 2. ist das Selbe wie https://github.com/cgoIT/calendar-extended-bundle/issues/9, es fehlen die URL Parameter. Kann es daran liegen?

PPS:
Wenn ich URL Parameter (zB `?day=20240720&times=1721473200,1721487600`) wie im related Issue  https://github.com/cgoIT/calendar-extended-bundle/issues/9 angesprochen, setzte, dann funktioniert die Ausgabe im Modul `EventLeser` wie bisher. 
Dass wirft den neuen Punkt auf dass jetzt im `Eventliste` die Links zum `EventLeser` keine URL Parameter mehr enthalten, obgleich die URL PArameter im `EventLeser` verwendet werden und funktionieren.


Anders gesagt:
Wenn die Links zum Leser die URL Parameter wieder hätten, würde wohl alles funktionieren, wie zuvor.

**Comment by cgoIT** [comment]
> Vielen Dank – auch das du dieses Plugin übernommen hast!
> 
> Beim Vergleich sind mir jetzt leider dennoch andere Fehler aufgefallen. Vorab: Ich verwende bei dem Test Event nur Wiederholungen (unregelmäßig). Und habe jetzt alles Möglichen Varianten getestet.
> 
> 1. Wird das Modul `Eventliste` mit dem Modul `Eventliste-Menü` angezeigt / gefiltert, dann fehlt in der Liste jeweils das erste / originale Event, es werden nur die Wiederholungen gezeigt.
> 2. Das Modul `EventLeser` mit dem Template `event_full` hatte früher in der Variable `begin` und evtl. auch in anderen Variablen immer das nächste Ereignis ausgegeben. Das klappt jetzt nicht mehr. Der selber Fehler findet sich analog in `recurring`. Die Ausgabe "Das nächste Ereignis findet statt am ..." ist falsch.
> 
> PS: ich denke Punkt 2. ist das Selbe wie #9, es fehlen die URL Parameter. Kann es daran liegen?
> 
> PPS: Wenn ich URL Parameter (zB `?day=20240720&times=1721473200,1721487600`) wie im related Issue #9 angesprochen, setzte, dann funktioniert die Ausgabe im Modul `EventLeser` wie bisher. Dass wirft den neuen Punkt auf dass jetzt im `Eventliste` die Links zum `EventLeser` keine URL Parameter mehr enthalten, obgleich die URL PArameter im `EventLeser` verwendet werden und funktionieren.
> 
> Anders gesagt: Wenn die Links zum Leser die URL Parameter wieder hätten, würde wohl alles funktionieren, wie zuvor.

Hi,

vielen Dank für deine Analysen. Wäre es möglich, dass du das in (ich vermute zwei) neue Tickets überführst? Und wenn es irgendwie möglich ist, vielleicht sogar mit einem entsprechenden Beispiel. Ich weiß nicht, ob das vom Aufwand her möglich ist, aber eine kleine Beispielinstallation (den SQL-Dump und die composer.json dazu) in der sich das nachvollziehen lässt. Ich weiß, dass ich nicht unaufwändig, aber wenn ich so in das Ticket #9 schaue, dann hätten wir uns da viel Hin und Her sparen können... ;)

**Comment by Metis77** [comment]
Die Fehler die ich gefunden habe, sind eigentlich nur die Folgen der fehlenden URL Parameter.
Dazu gibt es bereits das Ticket https://github.com/cgoIT/calendar-extended-bundle/issues/9

Wenn du es reproduzieren willst:
In der alten Installation: https://regensburger-eltern.de/veranstaltungen.html
Hier hatten die EventListen Links zum Eventleser immer auch URL Parameter mit date und time.

In der neuen Installation (dieses Plugin)  https://v2.regensburger-eltern.de/veranstaltungen fehlen die URL Parameter ganz.

Nur deshalb kommt es zu obigen beschriebenen Fehlern.
Ursache sind also die fehlenden URL Parameter aus Ticket https://github.com/cgoIT/calendar-extended-bundle/issues/9

Ich denke, da braucht es deshalb gar kein separates Ticket.

**Comment by Metis77** [comment]
Seite den letzten Änderungen funktioniert die Detailseite mit dem template `event_full` perfekt.

Allerdings ist jetzt wieder `startTime` und `endTime` im Modul `Eventliste` falsch.
Diesmal nicht leer, sondern einfach das originäre Event Date, anstatt der aktuellen Wiederholung, wie bisher.
Die URL Parameter enthalten aber jeweils die Korrekten Datums.

**Comment by pipkin46** [comment]
@Metis77 
Mach mich nicht schwach... ich stecke gerade in einer Live-Schaltung und hatte den Eindruck, es geht nun alles.
Wenn ich Dich richtig verstehe, sind Startzeit und Endzeit von unregelmäßigen Wiederholungen in der Eventliste falsch? Bei mir unter 5.3.11 und 2.4.3 scheint es zu gehen. Wo unterscheiden wir uns...?

**Comment by Metis77** [comment]
Hm ich habe nochmal alles durchgetestet. `startTime` ist für die Wiederholungen falsch.
Anbei eine Liste der Variablen, die ich getestet habe:

<img width="650" alt="Bildschirmfoto 2024-07-17 um 15 18 05" src="https://github.com/user-attachments/assets/f3e9da6a-97bc-4b93-a283-c3be7fc138d0">

Außerdem ist mir aufgefallen, dass nix mehr funktioniert, sobald ich zusätzlich zu den `Wiederholungen (unregelmäßig)` die `Wiederholungen (erweitert)` oder die normalen `Wiederholungen` verwenden möchte.
Das gehört zwar sicher in einen anderen Task, aber ich will hier auch nicht übertreiben ;)

**Comment by cgoIT** [comment]
Hi,
im Template `event_full` werden doch `startTime` und `endTime` gar nicht verwendet, oder? Nur `date`, `time` und `datetime`.
Im Prinzip ist es so, dass `begin` und `end` die "angepassten" Zeitpunkte (je nach Wiederholung) berücksichtig. `startTime` und `endTime`, etc. sind die originalen aus dem Event.

Und lässt sich das "nix mehr funktioniert" in dem Nachsatz noch etwas genauer spezifizieren?

**Comment by Metis77** [comment]
> Hi, im Template `event_full` werden doch `startTime` und `endTime` gar nicht verwendet, oder? Nur `date`, `time` und `datetime`. Im Prinzip ist es so, dass `begin` und `end` die "angepassten" Zeitpunkte (je nach Wiederholung) berücksichtig. `startTime` und `endTime`, etc. sind die originalen aus dem Event.

Ja, so sehe ich das jetzt auch und finde auch, dass das sinn ergibt.
Im alten Plugin war das aber anders – das Template anzupassen war jetzt aber kein Problem.

> 
> Und lässt sich das "nix mehr funktioniert" in dem Nachsatz noch etwas genauer spezifizieren?

Mir ist nur aufgefallen, wenn ich die normalen (contao) Event Wiederholungen oder die Wiederholungen (extended) dazu schalte, werden die des Plugins (unregelmäßig) nicht mehr angezeigt. Wenn ich dann die normalen wieder abschalte, werden die Wiederholungen (unregelmäßig) auch nicht wieder angestellt – obwohl im Backend angezeigt. Erst wenn ich über die Versionierung zurückging, kamen die wieder.
Weiter bin habe ich das jetzt aber nicht untersucht.

**Comment by pipkin46** [comment]
Hi,
ich lasse mir mit **this-> date** das Datum des Events ausgeben und mit **this->time** die Uhrzeiten, und zwar über event_liste.html5 und in event_full.html5. Ich habe ein Event mit regelmäßigen Wiederholungen + unregelmäßige Wiederholungen. Das sieht bei mir soweit korrekt aus. "Extended" Wiederholungen habe ich allerdings nicht im Einsatz.

Leider muss man nach dem Update auf Contao 5.3 sehr viele alte Templates neu anpassen. Die ganzen alten Event-Templates liefen bei mir auch nicht mehr. Aber das kann man ja der Erweiterung nicht zum Vorwurf machen.

Ich habe allerdings noch zwei, drei kleine Bugs entdeckt, und sobald ich Zeit habe, formuliere ich die mal aus und mache neu Reports dazu. Für den Moment bin ich heilfroh, dass es bis hierhin geht. Tausend Dank nochmal für die ganze Arbeit!!

**Comment by cgoIT** [comment]
> Mir ist nur aufgefallen, wenn ich die normalen (contao) Event Wiederholungen oder die Wiederholungen (extended) dazu schalte, werden die des Plugins (unregelmäßig) nicht mehr angezeigt. Wenn ich dann die normalen wieder abschalte, werden die Wiederholungen (unregelmäßig) auch nicht wieder angestellt – obwohl im Backend angezeigt. Erst wenn ich über die Versionierung zurückging, kamen die wieder.

Also ich habe das jetzt mal in meiner Testinstallation versucht nachzuvollziehen und konnte dabei keine Probleme feststellen. Hab erst die normalen, dann die erweiterten Wiederholungen mit den fixen (unregelmäßigen) Wiederholungen kombiniert und zum Schluss noch Ausnahmen hinzugefügt. Funktioniert bei mir aber alles korrekt. Du könntest mal schauen, wenn das Problem wieder bei dir auftritt, was im Feld allRecurrences steht, wenn du bei dem Event in der Liste im Backend auf das "i"-Symbol klickst (ganz rechts dort wo auch das Stift-Symbol ist).

**Comment by Metis77** [comment]
Ok, ich glaub ich habs gefunden:
Wenn man bei den normalen Contao Wiederholungen, einen Wochentag filtert, dann werden auch die Extended Wiederholungen nach diesem Wochentag gefiltert.

zB: 
In den normalen Contao Wiederholungen ist eingestellt, dass nur Wiederholungen die auf Dienstage fallen, angezeigt werden sollen.
Wenn dann eine extended Wiederholung nicht zufällig an einem Dienstag ist, dann wird die rausgefiltert.

Im Backend zeigt `allRecurrences` alle Wiederholungen an.
(selbst jene, die es aus den normalen Contao Wiederholungen nach dem Wochentagfilter garnicht geben sollte)

PS:
und das Beste zum Schluss:
Wenn man die normal Contao Filterung wieder ausschaltet, ohne vorher Checkboxen für die Wochentags Filter rauszunehmen, dann werden die Wochentage trotzdem weiter gefiltert.
