### ISSUE TITLE
Falsches Datum in der Detailansicht bei unregelmäßigen Terminen

### ISSUE THREAD

**Issue by pipkin46** [cgoIT/calendar-extended-bundle#17]
Ich hoffe, ich nerve nicht! ;-)

Seit dem Update 2.4.1 stimmen zwar die Uhrzeiten bei unregelmäßigen Wiederholungen, aber jetzt gibt $this->date ein falsches Event-Datum über das Template Event_full.html5 aus.

Eine Logik hat sich mir da noch nicht erschlossen. Es schien so, als wenn das Datum der ersten Wiederholung nach dem Orginal-Event ausgegeben wird, kann aber auch nicht korrekt sein. Das Datum bei den Original-Events stimmen, nur die Daten der unregelmäßigen Wiederholungen nicht.

Getestetes Beispiel:

Original-Event: 1.7.2024 -> Datum in Event_full/ Detailansicht korrekt
2 monatliche regelmäßige Wiederholungen:
1.8.2024 -> Datum in Event_full/ Detailansicht korrekt
1.9.2024 -> Datum in Event_full/ Detailansicht korrekt
1 unregelmäßige Wiederholung:
1.10.2024 -> Datum in Event_full/ Detailansicht **1.8.2024**

Ich stehe gern für Tests zur Verfügung. Kann ich irgendwas tun, um zu helfen?

**Comment by cgoIT** [comment]
Sollte mit dem Release 2.4.2 behoben sein.
