### ISSUE TITLE
Please, add the previous function eventcount

### ISSUE THREAD

**Issue by jankout** [cgoIT/calendar-extended-bundle#23]
Hello, 

in the original version, it was possible to use the function `eventcount` in the `mod_eventlist.html5`. Unfortunately, this function does not exist anymore in your version. That's why I would like to ask you to add it to your version. 
 
See [here](https://github.com/kmielke/calendar-extended-bundle/blob/e09c44fe5fcffcb62aa8adcd9f646deb28966f06/src/Resources/contao/modules/ModuleEventlist.php#L425) 

I would appreciate it very much. Thank you very much for your great work.

**Comment by cgoIT** [comment]
Hi @jankout,

this is already in there. Or better: it's part of the contao-calendar core functionality. But the value is `eventCount` and not `eventcount`.
If I add something like `<h4>Total events: <?= $this->eventCount; ?></h4>` I get the correct value in the frontend.

**Comment by jankout** [comment]
yes, you are right. I get to know it in Stack support too. Thank you very much for your help. We can close this issue. :-)
