### ISSUE TITLE
Ausnahmen und Wiederholungen neue Zeile erzeugen

### ISSUE THREAD

**Issue by marcoheinz** [cgoIT/calendar-extended-bundle#6]
Im Bereich "Ausnahmen und Wiederholungen" lassen sich mittels + Button keine weiteren Zeilen erzeugen.
Getestet unter 
4.13.43
php 8.1
Safari

**Comment by cgoIT** [comment]
Hi @marcoheinz,

könntest du mal testen, ob das mit der Version dev-main nun funktioniert? Danke!

**Comment by marcoheinz** [comment]
Kann ich gerne testen. Was muss ich im Contao Manager für eine Version eintragen?

**Comment by cgoIT** [comment]
dev-main

**Comment by marcoheinz** [comment]
Getestet. Funktioniert mit dev-main

**Comment by cgoIT** [comment]
Danke für das Feedback. Habe eben die Version 2.0.2 erstellt, die das Problem behebt.
