### ISSUE TITLE
URL Parameter fehlen

### ISSUE THREAD

**Issue by marcoheinz** [cgoIT/calendar-extended-bundle#9]
Es ist nicht mehr möglich aus einer Eventliste mit Wiederholungen einen bestimmten Tag anzuspringen. Es werden auch keine Parameter mehr an die URL gehängt ?day=xxx&times=xxx

**Comment by cgoIT** [comment]
Hi @marcoheinz,
ich verstehe noch nicht so ganz die Ausgangssituation. Du hast eine Eventliste. Darin werden x Events aufgelistet. Und wenn du jetzt auf ein Event klickst, dann fehlt was (ich vermute, dass ist es nicht, daher frage ich).
Ist das ein Event mit den Standard-Wiederholungen oder mit den erweiterten?

**Comment by marcoheinz** [comment]
Vllt. hilft hier ein Beispiel.


Der Wochenmarkt findet täglich außer Sonn-&Feiertags statt. 
Einstellungen: Event wiederholen > 1 Tag > Mo-Sa // Ausnahmen definieren = Feiertage nicht anzeigen

Wenn ich jetzt den Mo, 13. Mai anwähle sollte auf der Detailseite auch der 13. Mai angezeigt werden und nicht wie in dem Fall der 11. Mai.

**Comment by cgoIT** [comment]
Hi @marcoheinz,

wenn du zeitlich dazu kommst könntest du mal mit der Version `dev-main` testen, ob das nun so ist wie gewünscht.

**Comment by marcoheinz** [comment]
Hi,
die Parameter in der URL sind zurück und stimmen soweit auch.
Aber ... $this->begin liefert nicht das Datum aus den Parametern sondern das der nächste Wiederholung.

**Comment by cgoIT** [comment]
Hi @marcoheinz,
konnte ich nachstellen. Nun wird es so langsam etwas tricky. In der alten Version war es noch so, dass einige Standard-Klassen des Contao Calendar Bundles überschrieben wurden. Das will ich - wenn es irgendwie möglich ist - definitiv vermeiden. Ich habe einen neuen Version unter `dev-main` zur Verfügung gestellt. Wenn es für dich möglich ist, dann wäre ich dir super dankbar, wenn du das damit noch mal testen könntest. Vielen Dank schon mal im Voraus!

**Comment by marcoheinz** [comment]
> Ich habe einen neuen Version unter `dev-main` zur Verfügung gestellt. Wenn es für dich möglich ist, dann wäre ich dir super dankbar, wenn du das damit noch mal testen könntest. Vielen Dank schon mal im Voraus!

Habe eben die neue dev-main getestet. Problem besteht immer noch.

**Comment by cgoIT** [comment]
Mmmh, erst mal Danke für's testen. Vielleicht könntest du bitte noch mal kurz zwei Dinge beschreiben:

1. In welchen Modulen (EventReader, EventList, Calendar, ...) tritt das Problem auf?
2. Hast du die Standard-Templates dazu irgendwie angepasst?

**Comment by marcoheinz** [comment]
1. im eventreader
2. ja ist angepasst Datum hole ich über $this->begin. Habe aber auch mit Standard-Template getestet

**Comment by cgoIT** [comment]
Ok, ich habe zwar auch mit dem Standard-Template (`event_full.html5`) getestet, aber dann schaue ich da noch mal. D.h., um es noch mal zusammenzufassen, die URL zeigt auf eine Seite mit einem EventReader-Modul drauf und hat zwei Parameter (day im Format <JahrMonatTag> und times mit zwei Timestamps mit Komma getrennt). Korrekt?

**Comment by marcoheinz** [comment]
Das ist korrekt. Siehe auch obigen Link.
War denn dein Test mit dem event_full.html5 erfolgreich?

**Comment by cgoIT** [comment]
Ok, ich glaube ich habe den Fehler gefunden. Version ist im main-Branch. Falls es nicht geht, könntest du bitte mal kurz ein 
```
<?php $this->dumpTemplateVars(); ?>
```
in dein Event-Template packen und mir die Ausgabe davon hier zukommen lassen? Danke!

**Comment by marcoheinz** [comment]
Geht jetzt. Vielen dank!!
Zur Info: Mit dem neuen Branch wird mit 
`<?= $this->recurring ?><?php if ($this->until) echo ' ' . $this->until; ?>`
nichts mehr ausgegeben.

**Comment by cgoIT** [comment]
Hi,
auch das sollte nun behoben sein. Wenn ich nichts gegenteiliges von dir höre, dann mache ich heute Abend oder morgen früh eine neue Version fertig.
1000 Dank für's Testen!!!

**Comment by marcoheinz** [comment]
Mir ist in dem Zusammenhang noch was aufgefallen.
Bei der URL ohne Parameter sprich rel="canonical" wird das aktuelle Datum angezeigt auch wenn das Event an diesem Tag gar nicht geplant ist. Das gleiche bei Startzeit & Endzeit. Es wird immer die aktuelle Uhrzeit angezeigt was falsch ist. Getestet mit:
`<?= date('c', $this->begin); ?>`
`<?= date('c', $this->end); ?>`

Die kanonische URL im Falle von Wiederholungen sollte immer den nächsten Termin unter Berücksichtigung der Ausnahmen anzeigen.

**Comment by cgoIT** [comment]
Danke für den Hinweis. Habe ich noch behoben und eben eine neue Version erstellt.
[2.1.0](https://github.com/cgoIT/calendar-extended-bundle/releases/tag/v2.1.0)
